### ISSUE TITLE
Pull Request Commenter triggers twice

### ISSUE THREAD

**Issue by ryanisgrig** [southworkscom/SOUTHWORKS-azure-pipelines-tasks#21]
On my repository, we are attempting to use this task and *mostly* have it working. For some reason, each build on the Pull Request Validation triggers twice and I'm unable to discern where this is coming from. Our trigger looks identical to the sample provided, is there anywhere else I should look? I have other builds for specific projects that run only once, but these are using CI triggers.

Mainly I'm just trying to determine if this is something related to this task or a greater issue with our Azure Devops setup. Thanks!

**Trigger**
![image](https://user-images.githubusercontent.com/43043272/60212873-21c8fa80-9817-11e9-8dfd-ed76cbfd0bbc.png)

**Pull request sample**
![image](https://user-images.githubusercontent.com/43043272/60212907-3d340580-9817-11e9-9f1f-c84526a7f241.png)

**Comment by ParadoxARG** [comment]
Hi @ryanlengel,

We checked your PR, and we noticed that you have two pipelines running with a similar name. Is the task being triggered by both builds?

![image](https://user-images.githubusercontent.com/42191764/60215063-3d46fc00-983d-11e9-8fc3-6ce89eee2d14.png)

**Comment by ryanisgrig** [comment]
I was testing and disabling with multiple iterations, Github shows historically all the related builds to it. I'm investigating with someone on my team and it seems that all of our PR triggered builds are running twice, so I don't think this is related specifically to this task. Thanks!
