### ISSUE TITLE
GitHub PR Comment Task fails silently

### ISSUE THREAD

**Issue by BruceHaley** [southworkscom/SOUTHWORKS-azure-pipelines-tasks#27]
Expected behavior: When the GitHub PR Comment task does not successfully post to the PR, the task should show it failed.

Actual behavior: When the GitHub PR Comment task does not successfully post to the PR, the task shows success.

[This pipeline example](https://dev.azure.com/FuseLabs/SDK_Public/_build/results?buildId=303000&view=logs&j=a9861028-11aa-5b8a-9fa1-da2dce254972&t=601a0f4d-2518-568c-46c3-b8eb0272b4d2) repros the problem. Here the task, display name "Publish Compat Results to Github", fails to post with a "Bad credentials" error. Nevertheless, the task displays green for "succeeded" in the log summary. It should be displaying red.

**Comment by ceciliaavila** [comment]
Fixed in version 0.1.3
